# Generated by Django 2.2.10 on 2020-05-15 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('nname', models.CharField(max_length=100)),
                ('nrel', models.CharField(max_length=100)),
                ('pstatus', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('plantype', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('nshare', models.IntegerField()),
                ('polnum', models.IntegerField()),
                ('polterm', models.IntegerField()),
                ('prempayterm', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('ptotal', models.IntegerField()),
                ('svalue', models.IntegerField()),
                ('mvalue', models.IntegerField()),
                ('mbonus', models.IntegerField()),
                ('loanavl', models.BooleanField()),
                ('maxloan', models.IntegerField()),
                ('npreceipt', models.FileField(upload_to='recipts/')),
                ('age', models.IntegerField()),
                ('dob', models.DateField(blank='ture')),
                ('doc', models.DateField(blank='ture')),
                ('dom', models.DateField(blank='ture')),
                ('dop', models.DateField(blank='ture')),
                ('npamount', models.IntegerField()),
                ('npamountwt', models.IntegerField()),
                ('ppic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bpic', models.ImageField(default='default1.jpg', upload_to='bond_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
